include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/src/generated/**"

linter:
  rules:
    - always_declare_return_types
    - avoid_print
    - unawaited_futures
